### ISSUE TITLE
Install GNOME apps as flatpak

### ISSUE THREAD

**Issue by Blakyrin** [murkl/arch-os#72]
Thank you!, i've been using this for a while and i love it, but i think it would be better to install GNOME core apps as flatpak, or being able to not install them at all, as it's shipping unmantained apps as totem or evince

**Comment by murkl** [comment]
I'm glad to hear that. I like the idea, I have added a new property ARCH_OS_DESKTOP_SLIM_ENABLED in the dev branch. If this is set to 'true', a mimimal desktop is installed. Unfortunately the package 'sushi' is dependent on 'evince' which is why it is still included.

With preset 'desktop' and set ARCH_OS_DESKTOP_SLIM_ENABLED after that to 'true' these packages will be installed:
![Bildschirmfoto vom 2024-08-06 10-20-33](https://github.com/user-attachments/assets/c7058d13-180a-4522-8b0f-a3e5bf76dc47)

**Comment by murkl** [comment]
Is implemented in #71
